security:
    encoders:
        sisbeca\sisbecaBundle\Entity\XUser:
             algorithm:        sha512
             encode_as_base64: true
             iterations:       1
        Symfony\Component\Security\Core\User\User:
             algorithm: sha1       
             encode_as_base64: false
             iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        XUser:
            entity: { class: sisbeca\sisbecaBundle\Entity\XUser, property: login }
        in_memory:
            users:
                prueba: { password: 7c4a8d09ca3762af61e59520943dc26494f8941b, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        admin_area:
            pattern:    ^/usuario
            http_basic:
               realm: "Ingresa tu clave validad"
               provider: in_memory
            logout:
                path:   /principal/logout
                target: /usuario

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: sisbecaBundle_welcome
            logout:
                path:   /logout
                target: /login
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/welcome, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/validatestudent, roles: IS_AUTHENTICATED_ANONYMOUSLY }
